Repository dusk-network/plonk_gadgets, pull requests merged in 2020-08, with the labels that each got.

#11 Update the lib to the latest dusk-plonk version.
  Cargo.toml
  src/gadgets/boolean.rs
  src/gadgets/ecc.rs
  src/gadgets/errors.rs
  src/gadgets/mod.rs
  src/gadgets/scalar.rs
  src/gadgets/sk_knowledge.rs
Labels: area:cryptography, type:refactor, type:tech-debt

#14 Inverse range proof
  Cargo.lock
  Cargo.toml
  src/gadgets/scalar/range.rs
  src/gadgets/scalar/scalar.rs
Labels: area:cryptography, type:feature

#17 Adds Simple and Complex Rangeproof gadgets
  src/gadgets/scalar/range.rs
Labels: area:cryptography, type:refactor

#18 Update module structure and crate docs
  .travis.yml
  CONTRIBUTING.md
  Cargo.toml
  README.md
  src/allocated_scalar.rs
  src/errors.rs
  src/gadgets/mod.rs
  src/gadgets/scalar/mod.rs
  src/gadgets/scalar/range.rs
  src/lib.rs
  src/range.rs
  src/scalar.rs
  tests/range_gadgets_tests.rs
  tests/scalar_gadgets_tests.rs
Labels: area:documentation, type:feature, type:tech-debt

#21 Copyright headers addition
  Cargo.toml
  src/allocated_scalar.rs
  src/errors.rs
  src/lib.rs
  src/range.rs
  src/scalar.rs
  tests/range_gadgets_tests.rs
  tests/scalar_gadgets_tests.rs
Labels: documentation
